### PR TITLE
Destroy swiper instance on component destory

### PR DESCRIPTION
**Pull request by prosenjit-manna**
- This can fix memory leak

### CODE REVIEW

**Comment by JayChase** [comment]
Thanks for this. I completely missed that destroying Swiper had got left out of this version.

**Comment by prosenjit-manna** [comment]
Thanks for an awesome angular wrapper.

**Comment by prosenjit-manna** [comment]
Also for your information, The build process getting failed. 

Here is the solution https://github.com/ng-packagr/ng-packagr/issues/1411#issuecomment-537205616

**Comment by JayChase** [comment]
Thanks. I'll update all the ng libraries as well before making the next release,

**Comment by jdominguezpaz** [comment]
Hello, 
i think this is my first comment in a issue in github :D

The problem with this is if you try to destroy an uninitializated swiper you have an error on trying to destroy a not created object.

So... 
This could fix the problem:

    ngOnDestroy() {
        if (this.initialized) {
            this.swiper.destroy(true, true);
        }
    }

(I'm supposed to do a pull request? i'm a full stack dev freelance, my repos are mine. I did 0 pull request in my life :D)

**Comment by JayChase** [comment]
@jdominguezpaz Thanks for this. I'll get the change in the next version.

**Pull request merged**
